name: Test Main Server

on:
  push:
    branches: [develop]
    paths:
      - "main_server/**"
      - ".github/workflows/test_server.yml"
  pull_request:
    branches: [develop]
    paths:
      - "main_server/**"
      - ".github/workflows/test_server.yml"

jobs:
  setup:
    strategy:
      matrix:
        go-version:
          - 1.16.x
          - 1.17.x
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go-version }}"

  build:
    needs: setup
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: cd ./main_server && go build -v main.go

  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test Main Server
        run: cd ./main_server && go test -v -race ./test
